let D=null,chart=null,lastAlertKey="";const $=x=>document.getElementById(x),fmt=x=>x==null?"—":Number(x).toLocaleString("ar-LY",{minimumFractionDigits:2,maximumFractionDigits:4});
async function load(){try{let r=await fetch("/api/dashboard"),j=await r.json();D=j;let u=j.usd,p=j.parallel;$("obuy").textContent=fmt(u?.buy)+" د.ل";$("osell").textContent=fmt(u?.sell)+" د.ل";$("prate").textContent=fmt(p?.rate ?? p?.sell)+" د.ل";$("psource").textContent=p?.source||"—";$("pcity").textContent=p?`${p.city} • ${new Date(p.at).toLocaleString("ar-LY")}`:"لا توجد بيانات موازية متاحة";$("updated").textContent=j.official?.date||"—";$("state").textContent="متصل";renderBanks(j.banks);fillCurrencies(j.official?.rates||[]);historyChart();}catch(e){$("state").textContent="غير متصل"}}
function renderBanks(b){$("banksGrid").innerHTML=b.length?b.map(x=>`<article class="bank"><b>${x.name}</b><small>${x.city}</small><div><span>USD شراء</span><strong>${fmt(x.usdBuy)}</strong></div><div><span>USD بيع</span><strong>${fmt(x.usdSell)}</strong></div><div><span>EUR شراء</span><strong>${fmt(x.eurBuy)}</strong></div><div><span>EUR بيع</span><strong>${fmt(x.eurSell)}</strong></div></article>`).join(""):"<p>لم تُدخل بيانات المصارف بعد.</p>"}
async function historyChart(){if(!D)return;let r=await fetch("/api/history?currency=USD&days="+$("days").value),j=await r.json(),items=j.items;let labels=items.map(x=>new Date(x.at).toLocaleDateString("ar-LY")),off=items.map(x=>x.source==="official"?x.sell:null),par=items.map(x=>x.source==="parallel"?x.sell:null);if(chart)chart.destroy();chart=new Chart($("chart"),{type:"line",data:{labels,datasets:[{label:"الرسمي",data:off,spanGaps:true},{label:"الموازي",data:par,spanGaps:true}]},options:{responsive:true,plugins:{legend:{labels:{color:"#dce5ef"}}},scales:{x:{ticks:{color:"#8ea0b6"}},y:{ticks:{color:"#8ea0b6"}}}}})}
function fillCurrencies(a){$("cur").innerHTML=a.map((x,i)=>`<option value="${i}">${x.currency}</option>`).join("");updateConv()}
$("cur").onchange=updateConv;$("amt").oninput=updateConv;$("kind").onchange=updateConv;
function updateConv(){let x=D?.official?.rates?.[$("cur").value||0];if(x)$("out").textContent=fmt(Number($("amt").value||0)*x[$("kind").value])+" د.ل"}
async function notify(){if(!("Notification"in window))return alert("المتصفح لا يدعم الإشعارات");let p=await Notification.requestPermission();$("alertInfo").textContent=p==="granted"?"تم تفعيل إشعارات المتصفح. سيتم التحقق تلقائيًا ما دامت الصفحة مفتوحة.":"لم يتم السماح بالإشعارات."}
async function checkAlerts(){try{let r=await fetch("/api/alerts/check"),j=await r.json();if(!j.hits?.length)return;for(const h of j.hits){const key=h.id+":"+h.current;if(key===lastAlertKey)continue;lastAlertKey=key;if("Notification"in window&&Notification.permission==="granted")new Notification(h.name||"تنبيه سعر الصرف",{body:`${h.currency}: ${fmt(h.current)} د.ل`});$("alertInfo").textContent=`تنبيه: ${h.name||"تنبيه السعر"} — ${fmt(h.current)} د.ل`}}catch(e){}}
function admin(){location.href="/admin.html"} load();checkAlerts();setInterval(load,300000);setInterval(checkAlerts,60000);